export { default as Info } from "./Info";
export { default as Cart } from "./Cart";
export { default as Contact } from "./Contact";
export { default as Home } from "./Home";
export { default as Login } from "./Login";
export { default as Register } from "./Register";
export { default as SingleProduct } from "./SingleProduct";
export { default as Product } from "./product";
export { default as Create } from "./Create";
